### ISSUE TITLE
Commit .sym files to docs branch

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#533]
It's the canonical source of label addresses, and is stable across builds since it's sorted. Would be nice to have a copy available online without needing to rebuild the project locally.

As @yenatch notes, Travis can keep it updated: https://docs.travis-ci.com/user/deployment/pages/

(Minor point: pokecrystal.sym only, or pokecrystal11.sym too?)

**Comment by Rangi42** [comment]
We're turning [docs/](/docs/) into a site for the existing documentation, so Travis can force-push to a different branch instead, e.g. `syms` or `build`.

**Comment by coltongit** [comment]
@Rangi42 Also pokecrystal-au.sym

**Comment by coltongit** [comment]
I can help with getting this taken care of. Travis would need to generate the sym file for this by building the ROM and copying the generated symbol file over to docs, but this should be relatively easy to do.

**Comment by aaaaaa123456789** [comment]
Commit both a .map and a .sym file for each built ROM, I'd say. Map files are also useful; I've even had to [parse them programmatically](https://gist.github.com/aaaaaa123456789/669a3f1640b5ba336b1437408fe12833) in the past.

**Comment by coltongit** [comment]
I agree with that. It's high time we knock this one out of the woods.

**Comment by coltongit** [comment]
It seems that Travis CI is planning to rewrite the way that deployments are made. Should we update the Travis script to support this new deployment method? A separate issue cpuld be made for this.

**Comment by aaaaaa123456789** [comment]
Is there a reason we have to use Travis for that at all? We could always use GitHub Actions, which are built into the repository.

**Comment by coltongit** [comment]
True, if you think that's easier to implement.

**Comment by coltongit** [comment]
Anyway... I'll see if a GitHub Actions script or something similar can be made to automate this.

**Comment by mid-kid** [comment]
@aaaaaa123456789 Commiting .sym and .map files to the main branch is a bad idea - they'll get out of sync if we don't make 100% sure they're rebuilt on each commit. The more we can automate the better, hence travis.

**Comment by aaaaaa123456789** [comment]
@mid-kid you do realize GitHub Actions can commit to any branch, right? Not to mention it wouldn't be a problem if they got rebuilt for every commit.

(They don't have to be committed. GitHub Actions have a specific way of uploading persistent build artifacts.)

**Comment by coltongit** [comment]
Even then, it's rebuilt as part of the Travis build script, so why not do some trickery to link Travis with GitHub Actions to ensure that .map and .sym files will always be built on every commit made here?

**Comment by mid-kid** [comment]
Github Actions or Travis who cares, just get it done.

**Comment by aaaaaa123456789** [comment]
I only really brought it up because someone mentioned having issues deploying with Travis. If Travis works, it works.

**Comment by entrpntr** [comment]
Here is an extremely dirty proof of concept for getting it to work as a GitHub Action. I feel deep shame about many of the methods I used below, but I was only trying things out to see how things worked (and stopped as soon as it worked both with and without a `build` branch present). Someone else can feel free to tear it apart from here if this is still a priority.

```yaml
# Create this file as .github/workflows/sym.yml
#
# GitHub Actions will automatically run a task to update .sym and .map files 
# in the build branch when commits are pushed to master.
#
# Actions > All workflows > Commit .sym and .map files > (commit) > build
#
name: "Commit .sym and .map files"
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: |
          sudo apt-get install make gcc git pkg-config flex bison libpng-dev
          ( cd
              git clone -b v0.4.0 --depth=1 https://github.com/rednex/rgbds
              sudo make -C rgbds install
              rm -rf rgbds
          )
          make compare      
      - name: commit
        run: |
          git fetch origin build 2>/dev/null || true
          git config user.name "GitHub Action"
          git config user.email "<>"
          git add -f *.sym *.map
          git commit -m "Update .sym and .map files"
          git checkout build 2>/dev/null || (git checkout --orphan build && git rm --cached $(git ls-files))
          git checkout master -- *.sym *.map
          git add *.sym *.map
          git commit --allow-empty -m "Update .sym and .map files"
          git push origin build
```
